# Generated by Django 6.0.3 on 2026-05-22 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsaccount',
            name='last_interest_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
