# Generated by Django 6.0.3 on 2026-05-28 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_memberdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrepayment',
            name='nepali_date',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='loanrepayment',
            name='paid_at',
            field=models.DateTimeField(),
        ),
    ]
