# Generated by Django 6.0.3 on 2026-05-28 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_loanrepayment_nepali_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrepayment',
            name='paid_at',
            field=models.DateField(),
        ),
    ]
