# Generated by Django 6.0.3 on 2026-06-11 05:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_account_accounttransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CooperativeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_equity', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('opening_equity_set', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cooperative Settings',
            },
        ),
        migrations.CreateModel(
            name='TrialBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_type', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], max_length=10)),
                ('bs_year', models.IntegerField()),
                ('bs_month', models.IntegerField(blank=True, null=True)),
                ('bs_month_name', models.CharField(blank=True, max_length=20)),
                ('fiscal_year', models.CharField(max_length=10)),
                ('start_date_ad', models.DateField()),
                ('end_date_ad', models.DateField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('is_auto_generated', models.BooleanField(default=False)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_statements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-bs_year', '-bs_month'],
                'unique_together': {('period_type', 'bs_year', 'bs_month')},
            },
        ),
    ]
