# Generated by Django 6.0.3 on 2026-06-21 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_loanrepayment_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='first_due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
