# Generated by Django 6.0.3 on 2026-06-24 11:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_loan_member_alter_penalty_member_borrower_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionEditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('savings_deposit', 'Savings Deposit'), ('savings_withdrawal', 'Savings Withdrawal'), ('savings_penalty', 'Savings Penalty'), ('income', 'Income'), ('expenditure', 'Expenditure')], max_length=30)),
                ('reference_id', models.UUIDField()),
                ('original_data', models.JSONField()),
                ('corrected_data', models.JSONField()),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True)),
                ('edited_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_edits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-edited_at'],
            },
        ),
    ]
